/** Auto-generated stubs: every export of the notification/email/SMS modules, neutered. */
export const DEFAULT_FROM_EMAIL: any = async (..._a: any[]) => ({ success: true })
export const sendBookingConfirmation: any = async (..._a: any[]) => ({ success: true })
export const sendBookingConfirmationSMS: any = async (..._a: any[]) => ({ success: true })
export const sendCheckInNotification: any = async (..._a: any[]) => ({ success: true })
export const sendCheckInSMS: any = async (..._a: any[]) => ({ success: true })
export const sendCheckOutNotification: any = async (..._a: any[]) => ({ success: true })
export const sendCheckOutSMS: any = async (..._a: any[]) => ({ success: true })
export const sendGroupMemberAddedNotification: any = async (..._a: any[]) => ({ success: true })
export const sendGroupMemberUpdatedNotification: any = async (..._a: any[]) => ({ success: true })
export const sendManagerCheckInNotification: any = async (..._a: any[]) => ({ success: true })
export const sendManagerCheckInSMS: any = async (..._a: any[]) => ({ success: true })
export const sendOnlineBookingAlert: any = async (..._a: any[]) => ({ success: true })
export const sendOnlineBookingAlertSMS: any = async (..._a: any[]) => ({ success: true })
export const sendSMS: any = async (..._a: any[]) => ({ success: true })
export const sendSMSWithFallback: any = async (..._a: any[]) => ({ success: true })
export const sendStaffWelcomeEmail: any = async (..._a: any[]) => ({ success: true })
export const sendStayExtensionNotification: any = async (..._a: any[]) => ({ success: true })
export const sendStayExtensionSMS: any = async (..._a: any[]) => ({ success: true })
export const sendTaskAssignmentEmail: any = async (..._a: any[]) => ({ success: true })
export const sendTaskAssignmentSMS: any = async (..._a: any[]) => ({ success: true })
export const sendTransactionalEmail: any = async (..._a: any[]) => ({ success: true })
export const sendWhatsApp: any = async (..._a: any[]) => ({ success: true })
export default {}
